### ISSUE TITLE
message: unknown err , errcode: -1

### ISSUE THREAD

**Issue by he426100** [linuxdeepin/linglong-hub#27]
### SUMMARY | 问题概要

安装任意软件均提示message: unknown err , errcode: -1

### STEPS TO REPRODUCE | 复现步骤

进入https://store.linglong.dev/，选择任意应用点install

### OBSERVED RESULT | 观察到的结果

install io.typora , please wait a few minutes...
message: unknown err , errcode: -1

### EXPECTED RESULT | 期望的结果

success

### linglong/app in linglong version | 玲珑本身/玲珑软件

linglong version: 1.3.3
wsl2-Ubuntu 22.04.1 LTS
5.15.57.1-microsoft-standard-WSL2

**Comment by hqh2010** [comment]
你好，感谢你反馈的问题。我们这边安装了22.04.1 LTS Ubuntu环境测试，未重现故障现象。你那边能否重新复测后备注下测试时间，然后把/var/log目录下的linglong 文件夹压缩上传下？

**Comment by he426100** [comment]
测试时间：2022-08-19 09:36
log: [linglong.zip](https://github.com/linuxdeepin/linglong-hub/files/9378604/linglong.zip)

**Comment by hqh2010** [comment]
> 测试时间：2022-08-19 09:36 log: [linglong.zip](https://github.com/linuxdeepin/linglong-hub/files/9378604/linglong.zip)

您好，您反馈的问题解决了吗？通过您反馈的日志，定位发现linglong-system-helper服务状态异常。
玲珑包的安装需要依赖linglong-system-helper服务，您可以按如下操作步骤排查：
1. 在终端使用id deepin-linglong 查看deepin-linglong用户是否存在。
2. 在终端使用ll-cli query qq后，使用ps -ef | grep ll-system-heler命令查询服务对应的进程是否被拉起，如果没有被拉起，请排查下服务deepin-linglong-SystemHelper.service未拉起的原因。

**Comment by he426100** [comment]
> 

我是windows下的wsl2，snap都跑不了，想到这个就理解了为啥玲珑不行
