### ISSUE TITLE
Project lacks necessary LICENSE files

### ISSUE THREAD

**Issue by linghengqian** [linuxdeepin/linglong-hub#32]
### SUMMARY | 问题概要

- Project lacks necessary LICENSE files.

### STEPS TO REPRODUCE | 复现步骤

- I don't think this step is needed for https://github.com/linuxdeepin/linglong-hub/commit/ed9cdb8d0e9060f03ec0e2d75e6af399ffb1298c .

### OBSERVED RESULT | 观察到的结果

- I don't think this step is needed for https://github.com/linuxdeepin/linglong-hub/commit/ed9cdb8d0e9060f03ec0e2d75e6af399ffb1298c. .

### EXPECTED RESULT | 期望的结果

- I expect Linglong Hub to set the LICENSE for this project, whether it is a strict commercial LICENSE, or a relatively loose LICENSE. It would be nice to adopt MIT or Apache V2 LICENSE like https://github.com/microsoft/winget-pkgs .

### linglong/app in linglong version | 玲珑本身/玲珑软件

- I don't think this step is needed for https://github.com/linuxdeepin/linglong-hub/commit/ed9cdb8d0e9060f03ec0e2d75e6af399ffb1298c.

### ADDITIONAL INFORMATION | 额外补充

- I don't think this step is needed for https://github.com/linuxdeepin/linglong-hub/commit/ed9cdb8d0e9060f03ec0e2d75e6af399ffb1298c .

**Comment by BLumia** [comment]
Do you mean you'd like to see a license field in the metadata of each app? cc @realwujing

**Comment by realwujing** [comment]
[LGPL-3.0 license](https://github.com/linuxdeepin/linglong-hub/blob/master/LICENSE)
