### ISSUE TITLE
在Ubuntu 22.04.1 LTS 下，尝试使用ll-cli安装软件时出现错误

### ISSUE THREAD

**Issue by Tangtangchannel** [linuxdeepin/linglong-hub#5]

**Comment by yjqg6666** [comment]
> 顺便提一句，安装玲珑时有一个报错： N: 由于文件'/home/tangtang/linglong-bin_1.3.3.4-1_amd64.deb'无法被用户'_apt'访问，已脱离沙盒并提权为根用户来进行下载。 - pkgAcquire::Run (13: 权限不够)

$ mkdir /tmp/ll && cp linglong*deb /tmp/ll && chown _apt:root /tmp/ll/linglong*deb 
$ sudo apt install /tmp/ll/linglong*deb
