### ISSUE TITLE
玲珑工具是否支持 openEuler ？

### ISSUE THREAD

**Issue by sober-wang** [linuxdeepin/linglong-hub#8]
### SUMMARY | 问题概要

玲珑工具是否支持 openEuler ？

### STEPS TO REPRODUCE | 复现步骤

玲珑工具是否支持 openEuler ？

### linglong/app in linglong version | 玲珑本身/玲珑软件

玲珑工具是否支持 openEuler ？

**Comment by realwujing** [comment]
未来会与欧拉社区合作推广玲珑包格式
